currentLuckNum = None

def setup(luckNum:int):
    currentLuckNum = luckNum

def isMatched(user_stdin:int, currentRange:list):
    if not(len(currentRange)==2):
        raise NonValidListContainer("currangeRange must be stored 2 values as a list")

    if not(currentLuckNum==None):
        if user_stdin==int(currentLuckNum):
            return True
        else:
            if user_stdin<int(currentLuckNum):
                currentRange[0] = user_stdin
            elif user_stdin>int(currentLuckNum):
                currentRange[1] = user_stdin
    else:
        raise JumpStartDisallowed("You must set the luckNum which auto generated by computer at first")

    return False

if __name__=="Decision":
    pass

if __name__=="__main__":
    raise NotAnEntryPoint("Please invoked by importing")