name: Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-contrib/go@v0.1.0
    - name: configuring enviorment
      run: ./configure
    - name: Test make
      run: make build
